name: Deploy Streamlit App

on:
  push:
    branches: [ "main" ] # Deploy on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Cloud
      uses: streamlit/streamlit-deploy-action@v0.1.0
      with:
        app-name: "multi-depth-pai-analysis"
        streamlit-key: ${{ secrets.STREAMLIT_KEY }}
        streamlit-sharing-id: ${{ secrets.STREAMLIT_SHARING_ID }}
        main-file: "multi_depth_analysis.py"
